// AUTO-GENERATED from rainholm-fish/server/engine.py (surface fish / locations / baits only).
// Regenerate with: python scripts/gen-content.py

export const RARITY: Record<string, { tier: number; label: string; color: string }> = {
  'common': { tier: 1, label: '常见', color: '#9fb2c4' },
  'uncommon': { tier: 2, label: '少见', color: '#7d9b6a' },
  'rare': { tier: 3, label: '稀有', color: '#5f7d9c' },
  'epic': { tier: 4, label: '史诗', color: '#c8843c' },
  'legendary': { tier: 5, label: '传说', color: '#e8b830' },
  'mythic': { tier: 6, label: '神话', color: '#e06c5a' },
}

export interface LocationDef {
  id: string
  name: string
  description: string
  unlockCost: number
  junkChance: number
  tagMult: Record<string, number>
  skyTop: string
  skyMid: string
  water: string
  bg?: string
}

export const LOCATIONS: LocationDef[] = [
  {
    id: 'mangrove_shoal',
    name: '红树林浅滩',
    description: '盘根错节的红树根扎进咸淡交界的浅水，退潮时露出满地跳动的小生物，气根迷宫里藏着伏击的眼睛。',
    unlockCost: 320,
    junkChance: 0.1,
    tagMult: {"brackish": 1.5, "armored": 1.3},
    skyTop: '#1b2a4a',
    skyMid: '#3a5a8c',
    water: '#13314a',
    bg: 'spots/spot_mangrove_shoal.jpg',
  },
  {
    id: 'whispering_mire',
    name: '耳语沼泽',
    description: '终年浮着薄雾的沼泽，腐木与水汽间似有低语，越往深处水色越黑，脚下的泥不时咕嘟冒泡。',
    unlockCost: 200,
    junkChance: 0.11,
    tagMult: {"swamp": 1.6, "nocturnal": 1.3, "poison": 1.4},
    skyTop: '#bfe3ff',
    skyMid: '#7fb8e6',
    water: '#2f6f86',
    bg: 'spots/spot_whispering_mire.jpg',
  },
  {
    id: 'starry_delta',
    name: '星河三角洲',
    description: '大河入海的扇形浅滩，洄游季一到，亿万带荧光的鱼群涌入，整片水面像把银河倒扣在脚下。',
    unlockCost: 480,
    junkChance: 0.09,
    tagMult: {"brackish": 1.3, "glowing": 1.4, "migratory": 1.6},
    skyTop: '#ffd9a8',
    skyMid: '#ff9e6b',
    water: '#c75b3a',
    bg: 'spots/spot_starry_delta.jpg',
  },
  {
    id: 'sunken_ruins',
    name: '沉没遗迹',
    description: '沉入海底的古城，断柱与残塔在幽蓝水光里若隐若现，退潮时才浮出水面，海藻间漂着说不清的低响。',
    unlockCost: 650,
    junkChance: 0.08,
    tagMult: {"deepsea": 1.4, "ancient": 1.7, "glowing": 1.3},
    skyTop: '#2a1f3d',
    skyMid: '#5b3a7a',
    water: '#241b3a',
    bg: 'spots/spot_sunken_ruins.jpg',
  },
  {
    id: 'geyser_falls',
    name: '间歇泉瀑布',
    description: '层层热泉自岩壁喷涌而下汇成温瀑，蒸汽终年不散，再冷的天这里也暖意融融。',
    unlockCost: 400,
    junkChance: 0.1,
    tagMult: {"fire": 1.4, "mineral": 1.6},
    skyTop: '#0e2a33',
    skyMid: '#1f6b73',
    water: '#0a3b44',
    bg: 'spots/spot_geyser_falls.jpg',
  },
  {
    id: 'crystal_cave',
    name: '水晶洞',
    description: '洞壁缀满巨大的六棱晶柱，每一束微光都被折射成漫天碎虹，洞中恒温，听得见水滴坠落的回响。',
    unlockCost: 800,
    junkChance: 0.07,
    tagMult: {"crystal": 1.7, "glowing": 1.4},
    skyTop: '#1a2230',
    skyMid: '#3d4a5e',
    water: '#16222e',
    bg: 'spots/spot_crystal_cave.jpg',
  },
  {
    id: 'moonlit_pond',
    name: '月光池塘',
    description: '一汪静谧的池水，倒映着永远停在黄昏的天空。水面偶有涟漪，像有什么在月色下游动。',
    unlockCost: 0,
    junkChance: 0.1,
    tagMult: {"freshwater": 1.2, "nocturnal": 1.5},
    skyTop: '#cfeefe',
    skyMid: '#8fd0e8',
    water: '#3a7e9e',
  },
  {
    id: 'reed_river',
    name: '芦苇河',
    description: '两岸芦苇沙沙作响，水流缓慢清澈，是练手的好去处。',
    unlockCost: 0,
    junkChance: 0.12,
    tagMult: {"freshwater": 1.3},
    skyTop: '#e8f4ff',
    skyMid: '#bfd8ef',
    water: '#5a7fa6',
    bg: 'spots/spot_reed_river.jpg',
  },
  {
    id: 'abyssal_trench',
    name: '深渊海沟',
    description: '深不见底的幽蓝海沟，越往下越冷，有微光在黑暗里游弋。',
    unlockCost: 300,
    junkChance: 0.08,
    tagMult: {"deepsea": 1.5, "glowing": 1.4},
    skyTop: '#3a0d12',
    skyMid: '#7a1f1f',
    water: '#2a0a0a',
    bg: 'spots/spot_abyssal_trench.jpg',
  },
  {
    id: 'floating_lake',
    name: '浮空之湖',
    description: '悬在云端的一汪湖水，风从下方穿过，湖面像一面倒扣的镜子。',
    unlockCost: 600,
    junkChance: 0.09,
    tagMult: {"fantasy": 1.4, "wind": 1.5},
    skyTop: '#bcd8ff',
    skyMid: '#7fa8e6',
    water: '#3a6fae',
    bg: 'spots/spot_floating_lake.jpg',
  },
  {
    id: 'lava_spring',
    name: '熔岩温泉',
    description: '翻涌着橙红气泡的温泉，水里游着不怕烫的奇异生物。仅夏季开放。',
    unlockCost: 550,
    junkChance: 0.1,
    tagMult: {"fire": 1.6},
    skyTop: '#461a0a',
    skyMid: '#a8431a',
    water: '#5a1f0a',
    bg: 'spots/spot_lava_spring.jpg',
  },
]

export const LOCATION_BY_ID: Record<string, LocationDef> = Object.fromEntries(LOCATIONS.map(l => [l.id, l]))

export interface BaitEffects {
  rarityMult?: Record<string, number>
  tagMult?: Record<string, number>
  junkMult?: number
}
export interface BaitDef {
  id: string
  name: string
  cost: number
  description: string
  effects: BaitEffects
}

export const BAITS: BaitDef[] = [
  {
    id: 'basic_worm',
    name: '普通蚯蚓',
    cost: 10,
    description: '最朴素的蚯蚓，没有任何特殊效果，胜在便宜。',
    effects: {},
  },
  {
    id: 'glow_bait',
    name: '夜光饵',
    cost: 35,
    description: '在黑暗中散发幽幽蓝光，对夜行性鱼类格外有吸引力。',
    effects: {"rarityMult": {"rare": 1.5, "epic": 1.3}, "tagMult": {"nocturnal": 2.0}, "junkMult": 0.8},
  },
  {
    id: 'golden_lure',
    name: '黄金亮片',
    cost: 80,
    description: '华丽的金色旋转亮片，专挑大货：压住普通小鱼的咬口、把机会让给稀有及以上的稀客，还更少缠上杂物。（这片水域有稀有鱼时才划算）',
    effects: {"rarityMult": {"common": 0.5, "uncommon": 0.8, "rare": 1.4, "epic": 1.6, "legendary": 2.0, "mythic": 2.0}, "junkMult": 0.7},
  },
]

export const BAIT_BY_ID: Record<string, BaitDef> = Object.fromEntries(BAITS.map(b => [b.id, b]))

export interface FishDef {
  id: string
  name: string
  rarity: string
  tier: number
  color: string
  minW: number
  maxW: number
  unit: string
  value: number
  locations: string[]
  tags: string[]
  img?: string
}

export const FISH: FishDef[] = [
  {
    id: 'mud_carp',
    name: '泥鲤',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 10,
    maxW: 35,
    unit: 'cm',
    value: 11,
    locations: ["moonlit_pond", "reed_river", "whispering_mire", "starry_delta"],
    tags: ["freshwater"],
    img: 'fish/mud_carp.png',
  },
  {
    id: 'ghost_shrimp',
    name: '幽灵虾',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 3,
    maxW: 12,
    unit: 'cm',
    value: 10,
    locations: ["moonlit_pond", "reed_river", "mangrove_shoal", "whispering_mire", "starry_delta"],
    tags: ["freshwater", "nocturnal"],
    img: 'fish/ghost_shrimp.png',
  },
  {
    id: 'flicker_minnow',
    name: '荧鳞鲦',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 4,
    maxW: 14,
    unit: 'cm',
    value: 9,
    locations: ["moonlit_pond", "reed_river"],
    tags: ["freshwater", "nocturnal"],
    img: 'fish/flicker_minnow.png',
  },
  {
    id: 'angler_fry',
    name: '灯鮟鱇',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 4,
    maxW: 18,
    unit: 'cm',
    value: 12,
    locations: ["abyssal_trench", "sunken_ruins"],
    tags: ["deepsea", "glowing"],
  },
  {
    id: 'sky_skipper',
    name: '跃空鱼',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 8,
    maxW: 22,
    unit: 'cm',
    value: 12,
    locations: ["floating_lake", "starry_delta"],
    tags: ["fantasy", "wind"],
  },
  {
    id: 'frost_drifter',
    name: '霜漂鱼',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 6,
    maxW: 20,
    unit: 'cm',
    value: 11,
    locations: ["floating_lake", "starry_delta"],
    tags: ["fantasy", "wind"],
  },
  {
    id: 'scorched_tetra',
    name: '焦鳞灯鱼',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 5,
    maxW: 15,
    unit: 'cm',
    value: 13,
    locations: ["lava_spring", "geyser_falls"],
    tags: ["fire"],
  },
  {
    id: 'shard_fish',
    name: '晶片鱼',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 7,
    maxW: 18,
    unit: 'cm',
    value: 12,
    locations: ["crystal_cave"],
    tags: ["crystal", "glowing"],
  },
  {
    id: 'jelly_phantom',
    name: '幻水母',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 8,
    maxW: 25,
    unit: 'cm',
    value: 11,
    locations: ["floating_lake", "crystal_cave"],
    tags: ["fantasy", "glowing"],
  },
  {
    id: 'winter_cinder',
    name: '冬烬鱼',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 5,
    maxW: 14,
    unit: 'cm',
    value: 11,
    locations: ["lava_spring", "geyser_falls"],
    tags: ["fire"],
  },
  {
    id: 'silver_pike',
    name: '银梭鱼',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 20,
    maxW: 55,
    unit: 'cm',
    value: 26,
    locations: ["moonlit_pond", "reed_river"],
    tags: ["freshwater"],
    img: 'fish/silver_pike.png',
  },
  {
    id: 'dusk_eel',
    name: '暮色鳗',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 25,
    maxW: 60,
    unit: 'cm',
    value: 24,
    locations: ["moonlit_pond", "reed_river", "mangrove_shoal", "whispering_mire"],
    tags: ["freshwater", "nocturnal"],
    img: 'fish/dusk_eel.png',
  },
  {
    id: 'copper_bream',
    name: '铜鲂',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 18,
    maxW: 45,
    unit: 'cm',
    value: 22,
    locations: ["moonlit_pond", "reed_river", "whispering_mire"],
    tags: ["freshwater", "armored"],
    img: 'fish/copper_bream.png',
  },
  {
    id: 'cinder_loach',
    name: '余烬泥鳅',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 10,
    maxW: 28,
    unit: 'cm',
    value: 28,
    locations: ["lava_spring", "geyser_falls"],
    tags: ["fire"],
  },
  {
    id: 'deep_sculpin',
    name: '深岩杜父鱼',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 15,
    maxW: 40,
    unit: 'cm',
    value: 30,
    locations: ["abyssal_trench", "sunken_ruins"],
    tags: ["deepsea", "armored"],
  },
  {
    id: 'mangrove_snapper',
    name: '红树鲷',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 20,
    maxW: 50,
    unit: 'cm',
    value: 25,
    locations: ["mangrove_shoal"],
    tags: ["brackish", "armored"],
    img: 'fish/mangrove_snapper.png',
  },
  {
    id: 'winter_betta',
    name: '雪华斗鱼',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 12,
    maxW: 30,
    unit: 'cm',
    value: 27,
    locations: ["moonlit_pond", "reed_river", "floating_lake", "starry_delta"],
    tags: ["freshwater", "fantasy"],
    img: 'fish/winter_betta.png',
  },
  {
    id: 'zephyr_dancer',
    name: '流风舞者',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 15,
    maxW: 40,
    unit: 'cm',
    value: 24,
    locations: ["floating_lake", "starry_delta"],
    tags: ["wind", "fantasy"],
  },
  {
    id: 'geyser_wyrm',
    name: '间歇泉龙',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 30,
    maxW: 80,
    unit: 'cm',
    value: 29,
    locations: ["lava_spring", "geyser_falls"],
    tags: ["fire", "fantasy"],
  },
  {
    id: 'crystal_angler',
    name: '晶刺鮟鱇',
    rarity: 'rare',
    tier: 3,
    color: '#5f7d9c',
    minW: 15,
    maxW: 45,
    unit: 'cm',
    value: 100,
    locations: ["crystal_cave", "abyssal_trench"],
    tags: ["deepsea", "glowing", "crystal"],
  },
  {
    id: 'stormray',
    name: '风暴鳐',
    rarity: 'rare',
    tier: 3,
    color: '#5f7d9c',
    minW: 40,
    maxW: 80,
    unit: 'cm',
    value: 110,
    locations: ["floating_lake", "starry_delta"],
    tags: ["fantasy", "wind", "electric"],
  },
  {
    id: 'magma_salamander',
    name: '岩浆蝾螈',
    rarity: 'rare',
    tier: 3,
    color: '#5f7d9c',
    minW: 25,
    maxW: 55,
    unit: 'cm',
    value: 120,
    locations: ["lava_spring", "geyser_falls"],
    tags: ["fire", "fantasy"],
  },
  {
    id: 'void_jellyfish',
    name: '虚空水母',
    rarity: 'epic',
    tier: 4,
    color: '#c8843c',
    minW: 50,
    maxW: 90,
    unit: 'cm',
    value: 200,
    locations: ["abyssal_trench", "sunken_ruins"],
    tags: ["deepsea", "glowing", "shadow"],
  },
  {
    id: 'cloud_serpent',
    name: '云鳞蛟',
    rarity: 'epic',
    tier: 4,
    color: '#c8843c',
    minW: 60,
    maxW: 130,
    unit: 'cm',
    value: 220,
    locations: ["floating_lake", "starry_delta"],
    tags: ["fantasy", "wind", "migratory"],
  },
  {
    id: 'ember_barb',
    name: '烬棘鱼',
    rarity: 'epic',
    tier: 4,
    color: '#c8843c',
    minW: 35,
    maxW: 65,
    unit: 'cm',
    value: 180,
    locations: ["lava_spring", "geyser_falls"],
    tags: ["fire", "armored"],
  },
  {
    id: 'moon_phoenix_fish',
    name: '月凰鱼',
    rarity: 'legendary',
    tier: 5,
    color: '#e8b830',
    minW: 50,
    maxW: 90,
    unit: 'cm',
    value: 450,
    locations: ["moonlit_pond"],
    tags: ["freshwater", "nocturnal", "fantasy"],
    img: 'fish/moon_phoenix_fish.png',
  },
  {
    id: 'starwhale',
    name: '星鲸',
    rarity: 'legendary',
    tier: 5,
    color: '#e8b830',
    minW: 200,
    maxW: 450,
    unit: 'cm',
    value: 480,
    locations: ["abyssal_trench", "floating_lake"],
    tags: ["deepsea", "fantasy", "glowing"],
  },
  {
    id: 'time_eater',
    name: '时噬鱼',
    rarity: 'mythic',
    tier: 6,
    color: '#e06c5a',
    minW: 1,
    maxW: 999,
    unit: 'cm',
    value: 1000,
    locations: ["all"],
    tags: ["fantasy", "shadow", "deepsea"],
  },
  {
    id: 'bog_creeper',
    name: '沼行鱼',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 8,
    maxW: 22,
    unit: 'cm',
    value: 12,
    locations: ["whispering_mire"],
    tags: ["freshwater", "swamp", "nocturnal"],
  },
  {
    id: 'bloat_toadfish',
    name: '鼓蟾鱼',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 15,
    maxW: 38,
    unit: 'cm',
    value: 27,
    locations: ["whispering_mire"],
    tags: ["freshwater", "swamp", "poison"],
  },
  {
    id: 'wraithwood_fish',
    name: '朽木灵鱼',
    rarity: 'rare',
    tier: 3,
    color: '#5f7d9c',
    minW: 25,
    maxW: 55,
    unit: 'cm',
    value: 105,
    locations: ["whispering_mire"],
    tags: ["freshwater", "swamp", "nocturnal", "poison"],
  },
  {
    id: 'star_sand_darter',
    name: '星沙镖鲈',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 6,
    maxW: 16,
    unit: 'cm',
    value: 12,
    locations: ["starry_delta"],
    tags: ["brackish", "glowing", "migratory"],
  },
  {
    id: 'tidal_trout',
    name: '潮信鳟',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 30,
    maxW: 60,
    unit: 'cm',
    value: 26,
    locations: ["starry_delta"],
    tags: ["brackish", "migratory", "fantasy"],
  },
  {
    id: 'star_barge_whisker',
    name: '星舟巨鲶',
    rarity: 'epic',
    tier: 4,
    color: '#c8843c',
    minW: 120,
    maxW: 220,
    unit: 'cm',
    value: 220,
    locations: ["starry_delta"],
    tags: ["brackish", "fantasy", "glowing", "migratory"],
  },
  {
    id: 'urn_hermit',
    name: '瓮居蟹',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 5,
    maxW: 15,
    unit: 'cm',
    value: 11,
    locations: ["sunken_ruins"],
    tags: ["deepsea", "ancient"],
  },
  {
    id: 'rune_cod',
    name: '铭文鳕',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 30,
    maxW: 65,
    unit: 'cm',
    value: 28,
    locations: ["sunken_ruins"],
    tags: ["deepsea", "ancient", "glowing"],
  },
  {
    id: 'sunken_wraith',
    name: '沉城幽魂鱼',
    rarity: 'epic',
    tier: 4,
    color: '#c8843c',
    minW: 70,
    maxW: 130,
    unit: 'cm',
    value: 230,
    locations: ["sunken_ruins"],
    tags: ["deepsea", "ancient", "glowing", "shadow"],
  },
  {
    id: 'sulfur_killie',
    name: '硫华鳉',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 4,
    maxW: 12,
    unit: 'cm',
    value: 13,
    locations: ["geyser_falls"],
    tags: ["fire", "mineral"],
  },
  {
    id: 'steam_ray',
    name: '蒸汽鳐',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 35,
    maxW: 70,
    unit: 'cm',
    value: 29,
    locations: ["geyser_falls"],
    tags: ["fire", "mineral"],
  },
  {
    id: 'magma_peacock_bass',
    name: '熔岩孔雀鲷',
    rarity: 'rare',
    tier: 3,
    color: '#5f7d9c',
    minW: 28,
    maxW: 52,
    unit: 'cm',
    value: 110,
    locations: ["geyser_falls"],
    tags: ["fire", "mineral", "fantasy"],
  },
  {
    id: 'mudskipper_perch',
    name: '泥蟹攀鲈',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 12,
    maxW: 28,
    unit: 'cm',
    value: 11,
    locations: ["mangrove_shoal"],
    tags: ["brackish", "armored"],
    img: 'fish/mudskipper_perch.png',
  },
  {
    id: 'root_dragon',
    name: '气根龙',
    rarity: 'rare',
    tier: 3,
    color: '#5f7d9c',
    minW: 40,
    maxW: 75,
    unit: 'cm',
    value: 95,
    locations: ["mangrove_shoal"],
    tags: ["brackish", "fantasy"],
    img: 'fish/root_dragon.png',
  },
  {
    id: 'prism_lanternfish',
    name: '棱镜灯鱼',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 10,
    maxW: 25,
    unit: 'cm',
    value: 28,
    locations: ["crystal_cave"],
    tags: ["crystal", "glowing"],
  },
  {
    id: 'shard_shrimp',
    name: '碎晶虾',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 12,
    maxW: 30,
    unit: 'cm',
    value: 30,
    locations: ["crystal_cave"],
    tags: ["crystal", "armored"],
  },
  {
    id: 'crystal_leviathan',
    name: '洞天晶龙',
    rarity: 'legendary',
    tier: 5,
    color: '#e8b830',
    minW: 150,
    maxW: 280,
    unit: 'cm',
    value: 480,
    locations: ["crystal_cave"],
    tags: ["crystal", "glowing", "fantasy"],
  },
  {
    id: 'crucian',
    name: '鲫鱼',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 8,
    maxW: 25,
    unit: 'cm',
    value: 11,
    locations: ["moonlit_pond", "reed_river"],
    tags: ["freshwater"],
    img: 'fish/crucian.png',
  },
  {
    id: 'silver_dace',
    name: '银鲦',
    rarity: 'common',
    tier: 1,
    color: '#9fb2c4',
    minW: 6,
    maxW: 18,
    unit: 'cm',
    value: 10,
    locations: ["reed_river"],
    tags: ["freshwater"],
    img: 'fish/silver_dace.png',
  },
  {
    id: 'reed_perch',
    name: '芦苇鲈',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 15,
    maxW: 40,
    unit: 'cm',
    value: 22,
    locations: ["reed_river", "moonlit_pond"],
    tags: ["freshwater"],
    img: 'fish/reed_perch.png',
  },
  {
    id: 'glow_jelly',
    name: '光水母',
    rarity: 'uncommon',
    tier: 2,
    color: '#7d9b6a',
    minW: 10,
    maxW: 35,
    unit: 'cm',
    value: 28,
    locations: ["abyssal_trench"],
    tags: ["deepsea", "glowing", "nocturnal"],
  },
  {
    id: 'moonscale_carp',
    name: '月鳞鲤',
    rarity: 'rare',
    tier: 3,
    color: '#5f7d9c',
    minW: 20,
    maxW: 60,
    unit: 'cm',
    value: 80,
    locations: ["moonlit_pond"],
    tags: ["freshwater", "nocturnal"],
    img: 'fish/moonscale_carp.png',
  },
  {
    id: 'ember_carp',
    name: '熔岩鲤',
    rarity: 'rare',
    tier: 3,
    color: '#5f7d9c',
    minW: 18,
    maxW: 55,
    unit: 'cm',
    value: 110,
    locations: ["lava_spring"],
    tags: ["fire"],
  },
  {
    id: 'windveil_ray',
    name: '风纱鳐',
    rarity: 'epic',
    tier: 4,
    color: '#c8843c',
    minW: 25,
    maxW: 70,
    unit: 'cm',
    value: 180,
    locations: ["floating_lake"],
    tags: ["fantasy", "wind"],
  },
  {
    id: 'frostfin_eel',
    name: '霜鳍鳗',
    rarity: 'epic',
    tier: 4,
    color: '#c8843c',
    minW: 30,
    maxW: 90,
    unit: 'cm',
    value: 220,
    locations: ["abyssal_trench"],
    tags: ["deepsea", "glowing"],
  },
  {
    id: 'clockwork_koi',
    name: '发条锦鲤',
    rarity: 'legendary',
    tier: 5,
    color: '#e8b830',
    minW: 30,
    maxW: 80,
    unit: 'cm',
    value: 400,
    locations: ["floating_lake"],
    tags: ["fantasy"],
  },
  {
    id: 'the_first_drop',
    name: '「第一滴水」',
    rarity: 'mythic',
    tier: 6,
    color: '#e06c5a',
    minW: 1,
    maxW: 30,
    unit: 'cm',
    value: 1000,
    locations: ["all"],
    tags: ["fantasy"],
  },
  {
    id: 'fallen_star',
    name: '落星',
    rarity: 'rare',
    tier: 3,
    color: '#5f7d9c',
    minW: 15,
    maxW: 25,
    unit: 'cm',
    value: 888,
    locations: ["starry_delta"],
    tags: ["brackish", "glowing", "fantasy"],
    img: 'fish/fallen_star.png',
  },
]

export const FISH_BY_ID: Record<string, FishDef> = Object.fromEntries(FISH.map(f => [f.id, f]))

export const FIGHT_BY_RARITY: Record<string, number> = {"common": 0.7, "uncommon": 1.0, "rare": 1.25, "epic": 1.5, "legendary": 1.8, "mythic": 1.95}

export const JUNK_ITEMS = ['破靴子', '水草团', '小虾米', '易拉罐', '烂渔网']
